---
ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"


_hadoop:
  user: hadoop
  group: hadoop
  domain: "jtest.pivotal.io"
  base_path: "/home/hadoop"
  download: false
  firewall: false
  download_path: /tmp
  major_version: "3"
  minor_version: "3"
  patch_version: "6"
  bin_type: "tar.gz"
  download_url: "https://dlcdn.apache.org/hadoop/common"


_spark:
  domain: jtest.pivotal.io
  base_path: /home/spark
  download_path: /tmp
  worker:
    core: 6
    memory: "6G"
    default_core: 4
  download: false
  firewall: false
  user: "spark"
  group: "spark"
  major_version: 3
  minor_version: 5
  patch_version: 6
  bin_type: tgz
  download_url: "https://archive.apache.org/dist/spark"
  master_work_port: 7077
  worker_work_port: 7078
  master_ui_port: 8080
  worker_ui_port: 8081
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05", "rk9-node06", "rk9-node07" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05", "ubt24-node06", "ubt24-node07" ]
  debug_opt: ""  # --debug


_hbase:
  user: "{{ _hadoop.user }}"
  group: "{{ _hadoop.group }}"
  base_path: "{{ _hadoop.base_path }}"
  download: false
  firewall: false
  major_version: 2
  minor_version: 6
  patch_version: 1
  bin_type: tar.gz
  download_url: "https://archive.apache.org/dist/hbase"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_postgres:
  firewall: false
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_jdk:
  oss:
    install: true
    jvm_home: "/usr/lib/jvm"
    major_version: 11
    minor_version: 0
    patch_version: 4
    # 1.8.0
    # 11.0.4
    # 17.0.2
  oracle:
    install: false
    jvm_home: "/usr/lib/jvm"
    major_version: 13
    minor_version: 0
    patch_version: 2
    download: false


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"


kvm:
  hostname: "192.168.0.101"
  username: "root"
  password: "changeme"

